// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2AF12KTEsNhmvaSGr0xuuthmh0kV0jb4',
    appId: '1:330713103993:web:e3160e3e9acea2b1a09ea8',
    messagingSenderId: '330713103993',
    projectId: 'plantilla25-7dc89',
    authDomain: 'plantilla25-7dc89.firebaseapp.com',
    storageBucket: 'plantilla25-7dc89.appspot.com',
    measurementId: 'G-PSKE9E0W50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaRMMRWct1bG_j2WngztIp_qDTtWI9tOA',
    appId: '1:330713103993:android:c7fa7180c8120a68a09ea8',
    messagingSenderId: '330713103993',
    projectId: 'plantilla25-7dc89',
    storageBucket: 'plantilla25-7dc89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwvvdI7bqW3Eg9PnhRTNoJN6aF8niSOz0',
    appId: '1:330713103993:ios:a949abde5492802ba09ea8',
    messagingSenderId: '330713103993',
    projectId: 'plantilla25-7dc89',
    storageBucket: 'plantilla25-7dc89.appspot.com',
    iosClientId: '330713103993-l47f0v1hbp9s26pj4nbredi7ncts8dr9.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.landing25',
  );
}
